version: "3.1"

services:

  sf-nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    container_name: sf-nginx
    tty: true
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/sf-nginx.conf
      - ../../sfvel-tamduong/:/var/www/html/sfvel-tamduong
    depends_on:
      - sfvel-tamduong

  sfvel-tamduong:
    image: sfvel-tamduong
    build:
      args:
        user: kubikubo
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: sfvel-tamduong
    working_dir: /var/www/html/sfvel-tamduong
    tty: true
    volumes:
      - ../../sfvel-tamduong/:/var/www/html/sfvel-tamduong
      - ./php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    expose:
      - 9000

  sfvel-tamduong-worker:
    build:
        context: ./
        dockerfile: supervisor/Dockerfile
    container_name: sfvel-tamduong-worker
    volumes:
        - ../../sfvel-tamduong/:/var/www/html/sfvel-tamduong-worker
        - ./supervisor/:/etc/supervisor
        - ./php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini

  # sfvel-fe:
  #       container_name: sfvel-fe
  #       build:
  #           context: ./sfvel-fe
  #           dockerfile: Dockerfile
  #       restart: always
  #       tty: true
  #       volumes:
  #           - ../sfvel-fe/:/var/www/html/sfvel-fe
  #           - /app/node_modules
  #       ports:
  #           - 5173:5173

  sfmysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    container_name: sfmysql
    tty: true
    environment:
      MYSQL_DATABASE: sfmysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root

  sf-redis:
      image: redis
      container_name: sf-redis
      restart: always
      ports:
        - 6379:6379
      # environment:
      #   REDIS_REPLICATION_MODE: master
      #   REDIS_PASSWORD: sf@2023