version: "3.1"

services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    container_name: nginx
    tty: true
    volumes:
      - ${NGINX}
      - ${PHP_INFO}
      - ${LARAVEL_API}
    depends_on:
      - php-info

  php-info:
    image: php-info
    build:
      args:
        user: kubikubo
        uid: 1000
      context: ./php-info
      dockerfile: Dockerfile
    container_name: php-info
    working_dir: /var/www/html/phpinfo
    tty: true
    volumes:
      - ${PHP_INFO}
      - ./php-info/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    expose:
      - 9000

  sf-laravel-api:
    image: sf-laravel-api
    build:
      args:
        user: kubikubo
        uid: 1000
      context: ./sf-laravel-api
      dockerfile: Dockerfile
    container_name: sf-laravel-api
    working_dir: /var/www/html/sf-laravel-api
    tty: true
    volumes:
      - ${LARAVEL_API}
      - ./sf-laravel-api/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    expose:
      - 9000

  micro-a:
    image: micro-a
    build:
      args:
        user: kubikubo
        uid: 1000
      context: ./micro-a
      dockerfile: Dockerfile
    container_name: micro-a
    working_dir: /var/www/html/micro-a
    tty: true
    volumes:
      - ${LARAVEL_API}
      - ./micro-a/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    expose:
      - 9000

  micro-b:
    image: micro-b
    build:
      args:
        user: kubikubo
        uid: 1000
      context: ./micro-b
      dockerfile: Dockerfile
    container_name: micro-b
    working_dir: /var/www/html/micro-b
    tty: true
    volumes:
      - ${LARAVEL_API}
      - ./micro-b/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    expose:
      - 9000

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    container_name: mysql
    working_dir: /var/www/html/mysql
    tty: true
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: db_docker
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    depends_on:
      - php-info