###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"

services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
      - "443:443"
    container_name: nginx
    tty: true
    volumes:
      - ../phpinfo/:/var/www/html/phpinfo
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-info

  php-info:
    image: php-info
    build:
      args:
        user: kubikubo
        uid: 1000
      context: .
      dockerfile: Dockerfile
    container_name: php-info
    working_dir: /var/www/html
    tty: true
    volumes:
      - ../phpinfo/:/var/www/html/phpinfo
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    expose:
      - 9000

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    container_name: mysql
    working_dir: /var/www/html/mysql
    tty: true
    volumes:
      - ./phpdocker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: db_docker
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    depends_on:
      - php-info