version: "3.1"

services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    container_name: nginx
    tty: true
    volumes:
      - ./sf-laravel-api/sf-laravel-api-nginx.conf:/etc/nginx/conf.d/sf-laravel-api-nginx.conf
      - ../sf-laravel-api/:/var/www/html/sf-laravel-api
    depends_on:
      - sf-laravel-api

  sf-laravel-api:
    image: sf-laravel-api
    build:
      args:
        user: kubikubo
        uid: 1000
      context: ./sf-laravel-api
      dockerfile: Dockerfile
    container_name: sf-laravel-api
    working_dir: /var/www/html/sf-laravel-api
    tty: true
    volumes:
      - ../sf-laravel-api/:/var/www/html/sf-laravel-api
      - ./sf-laravel-api/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./sf-laravel-api/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    expose:
      - 9000

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    container_name: mysql
    tty: true
    volumes:
      - ${MYSQL}
    environment:
      MYSQL_DATABASE: sf_laravel_api
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root