version: "3.1"

services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    container_name: nginx
    tty: true
    volumes:
      - ${NGINX}
      - ${PHP_INFO}
      - ${LARAVEL_API}
      - ${MICRO_A}
      - ${MICRO_B}
    depends_on:
      - php-info
      - sf-laravel-api
      - micro-a
      - micro-b

  php-info:
    image: php-info
    build:
      args:
        user: kubikubo
        uid: 1000
      context: ./php-info
      dockerfile: Dockerfile
    container_name: php-info
    working_dir: /var/www/html/phpinfo
    tty: true
    volumes:
      - ${PHP_INFO}
      - ./php-info/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    expose:
      - 9000

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
    tty: true
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq
      - ./rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=1

  sf-laravel-api:
    image: sf-laravel-api
    build:
      args:
        user: kubikubo
        uid: 1000
      context: ./sf-laravel-api
      dockerfile: Dockerfile
    container_name: sf-laravel-api
    working_dir: /var/www/html/sf-laravel-api
    tty: true
    volumes:
      - ${LARAVEL_API}
      - ${LARAVEL_API_OVERRIDES}
    expose:
      - 9000

  micro-a:
    image: micro-a
    build:
      args:
        user: kubikubo
        uid: 1000
      context: ./micro-a
      dockerfile: Dockerfile
    container_name: micro-a
    working_dir: /var/www/html/micro-a
    tty: true
    volumes:
      - ${MICRO_A}
      - ${MICRO_A_OVERRIDES}
    expose:
      - 9000

  micro-b:
    image: micro-b
    build:
      args:
        user: kubikubo
        uid: 1000
      context: ./micro-b
      dockerfile: Dockerfile
    container_name: micro-b
    working_dir: /var/www/html/micro-b
    tty: true
    volumes:
      - ${MICRO_B}
      - ${MICRO_B_OVERRIDES}
    expose:
      - 9000

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    container_name: mysql
    tty: true
    volumes:
      - ${MYSQL}
      - ${MYSQL_MICRO_A}
      - ${MYSQL_MICRO_B}
    environment:
      MYSQL_DATABASE: kubikubo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    depends_on:
      - mysql-micro-a
      - mysql-micro-b

  mysql-micro-a:
    image: mysql-micro-a
    ports:
      - "3301:3306"
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql-micro-a
    working_dir: /var/www/html/mysql-micro-b
    tty: true
    volumes:
      - ${MYSQL_MICRO_A}
    environment:
      MYSQL_DATABASE: micro_a
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root

  mysql-micro-b:
    image: mysql-micro-b
    ports:
      - "3302:3306"
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql-micro-b
    working_dir: /var/www/html/mysql-micro-b
    tty: true
    volumes:
      - ${MYSQL_MICRO_B}
    environment:
      MYSQL_DATABASE: micro_b
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root