version: "3.1"

services:

  sfmysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    container_name: sfmysql
    tty: true
    environment:
      MYSQL_DATABASE: sfmysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root

  # sfmysql-1:
  #   image: sfmysql-1
  #   ports:
  #     - "3301:3306"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: sfmysql-1
  #   working_dir: /var/www/html/sfmysql-1
  #   tty: true
  #   environment:
  #     MYSQL_DATABASE: sfmysql1
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_PASSWORD: root

  # sfmysql-2:
  #   image: sfmysql-2
  #   ports:
  #     - "3302:3306"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: sfmysql-2
  #   working_dir: /var/www/html/sfmysql-2
  #   tty: true
  #   environment:
  #     MYSQL_DATABASE: sfmysql2
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_PASSWORD: root

  # sfmysql-3:
  #   image: mysql:8
  #   restart: always
  #   ports:
  #     - '4000:3306'
  #   command:
  #     - --character-set-server=utf8mb4
  #     - --collation-server=utf8mb4_unicode_ci
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=ghtk@123
  #   volumes:
  #     - ./mysql/initdb:/docker-entrypoint-initdb.d
  #     - ./mysql/data:/var/lib/mysql