version: "3.1"

services:

  sf-nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    container_name: sf-nginx
    tty: true
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/sf-nginx.conf
      - ../../sfvel-api/:/var/www/html/sfvel-api
    depends_on:
      - sfvel-api

  sfvel-api:
    image: sfvel-api
    build:
      args:
        user: kubikubo
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: sfvel-api
    working_dir: /var/www/html/sfvel-api
    tty: true
    volumes:
      - ../../sfvel-api/:/var/www/html/sfvel-api
      - ./php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    expose:
      - 9000

  # sfvel-api-worker:
  #       build:
  #           context: .
  #           dockerfile: sfvel-api/supervisor/Dockerfile
  #       container_name: sfvel-api-worker
  #       volumes:
  #           - ../../sfvel-api/:/var/www/html/sfvel-api-worker/
  #           - ./supervisor:/etc/supervisor/
  #           - ./php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini

  # sfvel-fe:
  #       container_name: sfvel-fe
  #       build:
  #           context: ./sfvel-fe
  #           dockerfile: Dockerfile
  #       restart: always
  #       tty: true
  #       volumes:
  #           - ../sfvel-fe/:/var/www/html/sfvel-fe
  #           - /app/node_modules
  #       ports:
  #           - 5173:5173

  sfmysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    container_name: sfmysql
    tty: true
    environment:
      MYSQL_DATABASE: sfmysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root

  sf-redis:
      image: redis
      container_name: sf-redis
      restart: always
      ports:
        - 6379:6379
      # environment:
      #   REDIS_REPLICATION_MODE: master
      #   REDIS_PASSWORD: sf@2023