FROM rabbitmq:3.12-management

EXPOSE 5672 15672

ENV RABBITMQ_DEFAULT_HOST=host.docker.internal
ENV RABBITMQ_DEFAULT_USER=guest
ENV RABBITMQ_DEFAULT_PASS=guest
# docker inspect rabbitmq #show id container rabbitmq