version: "3.1"

services:

  sf-nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    container_name: sf-nginx
    tty: true
    volumes:
      - ./policy-api/nginx.conf:/etc/nginx/conf.d/sf-nginx.conf
      - ./policy-fe/nginx.conf:/etc/nginx/conf.d/fe-nginx.conf
      - ../policy-api/:/var/www/html/policy-api
      - ../policy-fe/:/var/www/html/policy-fe
    depends_on:
      - policy-api
      - policy-fe

  policy-api:
    image: policy-api
    build:
      args:
        user: kubikubo
        uid: 1000
      context: ./policy-api
      dockerfile: Dockerfile
    container_name: policy-api
    working_dir: /var/www/html/policy-api
    tty: true
    volumes:
      - ../policy-api/:/var/www/html/policy-api
      - ./policy-api/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
      - ./policy-api/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    expose:
      - 9000

  policy-fe:
        container_name: policy-fe
        build:
            context: ./policy-fe
            dockerfile: Dockerfile
        restart: always
        tty: true
        volumes:
            - ../policy-fe/:/var/www/html/policy-fe
            - /app/node_modules
        ports:
            - 8081:8080

  sf-mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    container_name: sf-mysql
    tty: true
    volumes:
      - ${MYSQL}
    environment:
      MYSQL_DATABASE: sfvel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root